/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


uint32_t *RCC_AHB1ENR = (uint32_t*)0x40023830;

uint32_t *GPIOC_MODER = (uint32_t*)0x40020800;

uint32_t *GPIOC_ODR = (uint32_t*)0x40020814;


int main(void)

{

	*RCC_AHB1ENR |=(1<<2);		//ENABLING CLOCK

	*GPIOC_MODER |=(1<<12);		//SET THE MODER AS 12 = 1

	*GPIOC_MODER &=~(1<<13);	//SET THE MODER AT BIT 13=0

	while(1){

		*GPIOC_ODR &=~(1<<6);		//SET LED TO OFF STATE

		for(unsigned int i=0; i<100000; i++);	//ADD SOME DELAY

		*GPIOC_ODR |=(1<<6);		//SET THE LED ON STATE

		for(unsigned int i=0; i<100000; i++);

	}

}

