/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
uint32_t *AHB1ENR = (uint32_t*)0x40023830;
uint32_t *GPIOB_MODER=(uint32_t*)0x40020400;
uint32_t *GPIOC_MODER=(uint32_t*)0x40020800;
uint32_t *GPIOC_ODR = (uint32_t*)0x40020814;
uint32_t *GPIOB_IDR = (uint32_t*)0x40020410;
int main(void)
{
	*AHB1ENR |=(1<<1); //ENABLING CLOCK PORT B
	*AHB1ENR |=(1<<2); //ENABLING CLOCK PORT C
	*GPIOC_MODER |=(1<<18);//Setting BUZZER ON
	*GPIOC_MODER &=~(1<<19);
	*GPIOB_MODER &=~(1<<14);//SETTING SWITCH1 AS INPUT
	*GPIOB_MODER &=~(1<<15);
	while(1){
		uint8_t buttonstatus = (uint8_t)(*GPIOB_IDR &(1<<7));
		if(!(buttonstatus==0)){
			*GPIOC_ODR &=~(1<<9);

		}
		else{
			*GPIOC_ODR |=(1<<9);
		}
	}
}
